"""altered tables

Revision ID: 70e317af3008
Revises: c86a37e0e16e
Create Date: 2026-06-15 20:41:06.781741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70e317af3008'
down_revision: Union[str, Sequence[str], None] = 'c86a37e0e16e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'favorites', 'users', ['user_id'], ['id'])
    op.add_column('meals', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'meals', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'meals', type_='foreignkey')
    op.drop_column('meals', 'user_id')
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.drop_column('favorites', 'user_id')
    # ### end Alembic commands ###
