"""altered tables

Revision ID: 7617aaf147ac
Revises: f0d462ae3d8e
Create Date: 2026-07-01 20:21:49.029598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7617aaf147ac'
down_revision: Union[str, Sequence[str], None] = 'f0d462ae3d8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('target_calorie', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'target_calorie')
    # ### end Alembic commands ###
